---
deployment:
  tasks:
    - |
      if [[ $PWD == *"prod_repo"* ]]; then
        DEPLOYPATH=/home/yqukl8w3b3dr/public_html/public
      elif [[ $PWD == *"test_repo"* ]]; then
        DEPLOYPATH=/home/yqukl8w3b3dr/public_html/test
      else
        DEPLOYPATH=/home/yqukl8w3b3dr/public_html/dev
      fi
      echo "🚀 Desplegando en $DEPLOYPATH"

    - /bin/rsync -av --exclude='.git' --exclude='.env' --exclude='.cpanel.yml' ./ $DEPLOYPATH
    - /bin/find $DEPLOYPATH -type f -exec chmod 644 {} \;
    - /bin/find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - cd $DEPLOYPATH && php artisan optimize:clear
