---
deployment:
  tasks:
    # Ruta destino del despliegue
    - export DEPLOYPATH=/home/yqukl8w3b3dr/public_html
    - /bin/echo "🚀 Desplegando proyecto en $DEPLOYPATH"

    # Copiar archivos (sin .git, .env ni este archivo)
    - /bin/rsync -au --exclude='.git' --exclude='.env' --exclude='.cpanel.yml' ./ $DEPLOYPATH

    # Asignar permisos correctos
    - /bin/find $DEPLOYPATH -type f -exec chmod 644 {} \;
    - /bin/find $DEPLOYPATH -type d -exec chmod 755 {} \;

    # Limpiar cachés Laravel (solo si existe artisan)
    - if [ -f "$DEPLOYPATH/artisan" ]; then cd $DEPLOYPATH && php artisan view:clear && php artisan config:cache; fi

    - /bin/echo "✅ Despliegue completado correctamente"
